### ISSUE TITLE
About nonlinear component of instantaneous phase of BPSK

### ISSUE THREAD

**Issue by potato-cat** [jcqvisser/Automatic-Modulation-Classification#2]
I have a question that confused me for weeks. When I read your paper and found this feature σap which is used to distinguish BPSK and M-PSK. I do hilbert transform and calculate instantaneous phase, Then I remove linear component by subtracting 2*pi*i*fc/fs，however , I got a result that nonlinear component is a curve that contains 0, pi, 2pi, 3pi, ... I found this in Nandi's book. "BPSK does not have information in its absolute instantaneous phase (centred), because there are only two states for the instantaneous phase. When the instantaneous phase is centred at zero, their absolute
values are the same." In this view,  σap should be zero. So it should be a cycle like 0, pi, 0, pi.
This is my result,
![image](https://user-images.githubusercontent.com/21253825/78011578-58b7d800-7376-11ea-8eb1-9c7a7bc7bcee.png)
This is my nonlinear component of instantaneous phase.
![image](https://user-images.githubusercontent.com/21253825/78011614-63726d00-7376-11ea-9a20-b7fe4ca2980a.png)
I am almost crazy~~~ I don't know what I should do and I don't know where my error is.
I would appreciate it if you could help me with this.
Thank you!
Sincerely~

**Comment by ScooterDelta** [comment]
Hi there, unfortunately this project is not maintained. It was done during our studies but has not been touched or glanced at in the last 5 years. 

If you need help with these queries, unfortunately we will not be able to help you.
